### PR TITLE
Magsw state alert

### PR DESCRIPTION
**Pull request by zx100x100**
Add a heartbeat function that toggles the buzzer depending on which mag switches are active / batteries are plugged in.
The pattern is 2 short beeps if battery 1 is active, 1 long beep if battery 2 is active.

No batteries:
Silent

battery 1 active:
beep, beep, Pause

battery 2 active:
pause, beeeeeep

both batteries active:
beep, beep, beeeeeep

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
All of these whitespace issues would just go away if you ran a code formatter :wink: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-:-MChwmZrBdYqg0NXcp03:bm8abrg)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @AidanHa, @amihaila, @dwkletke, @jacobdeery, @JaredWatson, @QuantumManiac, @wendi-yu, and @zx100x100)

___
*[main.c, line 70 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChqvkk3szRxetKkm5P:-MChqvkk3szRxetKkm5Q:bdom6q6) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/main.c#L70)):*
> ```C
>             // Toggle the white LED
>             LATC5 = ~LATC5;
>             
> ```

remove leading whitespace
___
*[main.c, line 134 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChqx4i1QUWou23-1S-:-MChqx4i1QUWou23-1S0:bdom6q6) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/main.c#L134)):*
> ```C
>         // send queued messages
>         txb_heartbeat();
>         
> ```

remove leading whitespace
___
*[setup.h, line 12 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChr05EBIgM_h5SHVF0:-MChr05EBIgM_h5SHVF1:b-uv7i6k) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.h#L12)):*
> ```objc
> 
> #define UNDERVOLTAGE_THRESHOLD 5000 //in mV
>         
> ```

remove whitespace
___
*[setup.h, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChr437BACuKEJsscAj:-MChr437BACuKEJsscAk:bdom6q6) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.h#L38)):*
> ```objc
>   
>   void osc_init(void);
>   
> ```

remove leading whitespace
___
*[setup.c, line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChrC_mE2inVZUrO_Ix:-MChrC_mE2inVZUrO_Iy:b-syc6s3) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.c#L43)):*
> ```C
> static uint8_t indicator_state = 0;
> void indicator_buzzer_heartbeat(void){
>     
> ```

remove whitespace on all of these lines
___
*[setup.c, line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChrguMDO5lwYtqFV6g:-MChrguMDO5lwYtqFV6h:bstbz15) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.c#L47)):*
> ```
> (uint16_t)ADCC_GetSingleConversion(channel_BATTERY_1)*ANALOG_SCALLER
> ```
Please extract this as a named variable outside of the if statement
___
*[setup.c, line 49 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChs12U1onMrmvyTYzW:-MChs12U1onMrmvyTYzX:blxp4py) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.c#L49)):*
> ```
> indicator_state = 0;
> ```
it might be easier to just make this a `bool buzzer_on`, since we don't really need to keep track of what specific state we're in (we just care about toggling the buzzer)
___
*[setup.c, line 58 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChrmg17CiftHpIYQF0:-MChrmg17CiftHpIYQF1:b-yq8kh4) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.c#L58)):*
> ```
> (uint16_t)ADCC_GetSingleConversion(channel_BATTERY_2)*ANALOG_SCALLER
> ```
Same

**Review by wendi-yu — COMMENTED** [review]
I didn't have a ton to say except more format nitpicks, looks good overall :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-:-MCkTnxc7UPiLIbsCqFj:b-ykayu3)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @AidanHa, @amihaila, @dwkletke, @JaredWatson, @QuantumManiac, @wendi-yu, and @zx100x100)

___
*[main.c, line 135 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MCkRIWVA8AWY5e-q7U-:-MCkRIWVA8AWY5e-q7U0:bcobvei) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/main.c#L135)):*
> ```C
>         txb_heartbeat();
>         
>         //Mag-switch Arming Alert 
> ```

Maybe have a consistent style as to whether you have a space in front of the `//` or not?
___
*[setup.c, line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MCkRyrH2a6J100w1vwz:-MCkRyrH2a6J100w1vx-:but8jak) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.c#L47)):*
> ```C
>     
>     if(indicator_state != 0 && loop_time < 750 
>         && (uint16_t)ADCC_GetSingleConversion(channel_BATTERY_1)*ANALOG_SCALLER > UNDERVOLTAGE_THRESHOLD){
> ```

should `ANALOG_SCALLER` be `ANALOG_SCALER`?
___
*[setup.c, line 82 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MCkR99_08LWzer8I1sV:-MCkR99_08LWzer8I1sW:b-56aylt) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.c#L82)):*
> ```C
>     }
>     
> }
> ```

Missing final newline here :0

**Comment by QuantumManiac** [comment]
> should `ANALOG_SCALLER` be `ANALOG_SCALER`?

Or is it `ANALOG_SCALAR`?

If I remember correctly, some of these things were addressed on the initial code review, #3 , Taking a look at the code on master confirms that. Is this branch a bit behind?

But yeah, once the formatting issues are taken care of, you should be good to go in my mind.

**Comment by zx100x100** [comment]
I believe I have resolved all comments except for
> Please extract this as a named variable outside of the if statement

the function is intentionally written this way to avoid poling the ADC every time the function is called, only when a transition is needed, because polling the ADC is slow. if there is a more clear way to write this that accomplishes the same thing then I'm happy to change it.

**Review by jacobdeery — COMMENTED** [review]
Can you make it into a function, in that case? 

```
uint16_t battery1_active(void) {
    return (uint16_t)ADCC_GetSingleConversion(channel_BATTERY_1)*ANALOG_SCALAR > UNDERVOLTAGE_THRESHOLD)
}
```

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-:-ME7jLYC7WUw4u4Rkzlv:b-2u779y)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @AidanHa, @amihaila, @dwkletke, @JaredWatson, @QuantumManiac, and @zx100x100)

___
*[setup.c, line 49 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4#-MChs12U1onMrmvyTYzW:-ME7ib1lAIdtta36qflI:bkn4cot) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/1ac40136b7c84dd25472f67ca949859c68402148/setup.c#L49)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> indicator_state = 0;
> ```
it might be easier to just make this a `bool buzzer_on`, since we don't really need to keep track of what specific state we're in (we just care about toggling the buzzer)
</blockquote></details>

`buzzer_state` is ok, but `buzzer_on` is definitely more clear in my opinion. It's obvious what `buzzer_on = true` means, but `buzzer_state = false` can be ambiguous - does it mean the buzzer is off? not responding?

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/4)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @AidanHa, @amihaila, @dwkletke, @jacobdeery, @JaredWatson, @QuantumManiac, @wendi-yu, and @zx100x100)

**Pull request merged**
