### PR TITLE
Hardware v2 incorperation

### PR DESCRIPTION
**Pull request by zx100x100**
Add in support for the extra sensing on the V2 hardware.
there is a lot of noise on the battery current channel, and it doesn't help that I am trying to measure a few mA with a sensing channel that needs to go up to 10A. to help I've implemented some low pass filtering on this channel

other minor additions include:
- shortening the indicator buzzer on time to reduce power draw
- Add in support for reset command

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6)* status: 1 of 10 files reviewed, 5 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @JaredWatson, @wendi-yu, and @zx100x100)

___
*[error_checks.h, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURO-UY9cNFQ4xL5pNC:-MURO-UY9cNFQ4xL5pND:bu5ak9s) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.h#L5)):*
> ```objc
> 
> #include <stdbool.h>
> #include <stdint.h>
> ```

Why do we need this header?
___
*[error_checks.c, line 51 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MUROTve4U1VeG0gPSGB:-MUROTve4U1VeG0gPSGC:b6uld1t) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L51)):*
> ```C
>         curr_data[0] = (bus_curr >> 8) & 0xff;
>         curr_data[1] = (bus_curr >> 0) & 0xff;
>         
> ```

Extraneous whitespace throughout this function
___
*[error_checks.c, line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURP6F9AlWk3lNghqn7:-MURP6F9AlWk3lNghqn8:bu56wh5) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L120)):*
> ```
> #define alpha_low 0.95
> #define alpha_low_low 0.9975
> ```
What's the difference between these? When would I want to use one vs the other?
___
*[error_checks.c, line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURPZnX6z0pQPm7nIXk:-MURPZnX6z0pQPm7nIXl:biyxv5c) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L123)):*
> ```C
> double low_pass_curr = 0;
> double low_low_pass_curr = 0;
> double batt_curr_low_pass(void){
> ```

It doesn't look like the return value of this function is ever used.
___
*[main.c, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURPEoZ9gM0qbSGVYwO:-MURPEoZ9gM0qbSGVYwP:byp18fd) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/main.c#L1)):*
> ```C
> 
> ```

Remove

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @JaredWatson, and @zx100x100)

___
*[error_checks.c, line 48 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURTuwU884RMB8cU8tT:-MURTuwU884RMB8cU8tU:brly66e) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L48)):*
> ```C
>     uint16_t bus_curr = (uint16_t)(ADCC_GetSingleConversion(channel_CAN_CURR)*CAN_CURR_SCALAR);
>     if(bus_curr > BUS_OVERCURRENT_THRESHOLD){
>         uint8_t curr_data[2] = {0};
> ```

I might just be forgetting C but any reason the 0 is in braces?
___
*[main.c, line 83 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURUMGoAWeg5TEx1l5F:-MURUMGoAWeg5TEx1l5G:b-pt0uzl) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/main.c#L83)):*
> ```C
>             status_ok &= check_battery_voltage_error();
>             status_ok &= check_bus_overcurrent_error();
>             //TODO: CHECK IF Watch Dog timer widow violation has ocured
> ```

`window has occurred`?

**Comment by zx100x100** [comment]
> What's the difference between these? When would I want to use one vs the other?

Added a comment to indicate their response times. The low low pass filter is used for reporting on battery current draw as it gives a fairly accurate average, but at a 10s response time it is slow as heck to react to any changes (somewhat intentional as it helps filter blinking LEDs and whatnot).

> It doesn't look like the return value of this function is ever used.

Not yet ;)  To finish answering the above, the low pass filter removes most of the really problematic noise, but still jumps around a few mA. It will be used for deployment event detection so it needs to be relatively quick to respond.

**Comment by zx100x100** [comment]
> I might just be forgetting C but any reason the 0 is in braces?
It's a bit of shorthand that by partially initializing the array, the compiler will finish initializing the rest with zeros.
not sure what happens if you remove the braces, but presumably trying to set an array to an integer value isn't a good thing?

> window has occurred?
the PIC18f26k83 has a windowed watchdog timer, what this means is that it can be configured such that you must reset the watchdog within a certain window. too early or too late will cause a window violation and reset the microcontroller. there is a register that stores the reason for last reset and at some point I should write a check to see if the reason was the watchdog and if so send a warning message. (cause obviously the watchdog is a last resort and we don't want it going off)

**Review by jacobdeery — COMMENTED** [review]
Can you please respond to the comments on Reviewable? It makes it much easier to see what's been addressed.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-:-MUTd4s4ERgTsMSySais:bd9ye6l)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @JaredWatson, and @zx100x100)

___
*[error_checks.c, line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURP6F9AlWk3lNghqn7:-MUTdRcw-rbTTB_8LX6c:b-5s9zxq) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L120)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> #define alpha_low 0.95
> #define alpha_low_low 0.9975
> ```
What's the difference between these? When would I want to use one vs the other?
</blockquote></details>

What does "response time" mean in this context? Is this rise time or settling time or something else?

I think we should also denote what the actual cutoff frequency of the filter is.

I would actually prefer to see this as an explicit calculation, so that if we change either parameter we don't need to redo the calculation manually.
___
*[error_checks.c, line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURPZnX6z0pQPm7nIXk:-MUTidQr0ecw1jqCnHup:b-yzqacu) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L123)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

It doesn't look like the return value of this function is ever used.
</blockquote></details>

I am not a huge fan of having two different ways to access the low pass and low_low pass values. I would prefer returning either both values or neither value.

**Review by zx100x100 — COMMENTED** [review]
Sorry, I tried last night, but realize now I needed to login which is why it wasn't working.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-:-MUV_pW6-8zgjSx2WDxI:b-s0dng5)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @jacobdeery, @JaredWatson, and @zx100x100)

___
*[error_checks.c, line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURPZnX6z0pQPm7nIXk:-MUVbLFZDgHoEBAEZJlo:b-e0907z) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L123)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I am not a huge fan of having two different ways to access the low pass and low_low pass values. I would prefer returning either both values or neither value.
</blockquote></details>

Fair, will change

**Review by zx100x100 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @jacobdeery, @JaredWatson, and @zx100x100)

___
*[error_checks.c, line 120 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MURP6F9AlWk3lNghqn7:-MUW0pjj3sQZn-xj5rBJ:bvnrpcm) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/e8a19b9392385e7c86400c075e7672e0d2a6114d/error_checks.c#L120)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What does "response time" mean in this context? Is this rise time or settling time or something else?

I think we should also denote what the actual cutoff frequency of the filter is.

I would actually prefer to see this as an explicit calculation, so that if we change either parameter we don't need to redo the calculation manually.
</blockquote></details>

updated

**Review by jacobdeery — APPROVED** [review]
This looks fine from my side, just an outdated comment

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-:-MUgLUXG6Y_HkyV5KFq5:big41po)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @dwkletke, @JaredWatson, and @zx100x100)

___
*[error_checks.h, line 26 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_arming/6#-MUgL3NEBq0pwRBgQZBZ:-MUgL3NEBq0pwRBgQZB_:bdp6b1x) ([raw file](https://github.com/waterloo-rocketry/cansw_arming/blob/73befe9c993977a1542ba55432250f6440dfee9d/error_checks.h#L26)):*
> ```
> returns the value from the higher cutoff frequency filter
> ```
doesn't do this anymore

**Pull request merged**
